path = "/Users/tymoteusz/refac/ivynet/cli/testingtest_create_bls_key"
bls_path = "/Users/tymoteusz/.eigenlayer/operator_keys"
mainnet_rpc_url = "https://rpc.flashbots.net/fast"
holesky_rpc_url = "https://eth-holesky.public.blastapi.io"
local_rpc_url = "http://localhost:8545"
default_ecdsa_keyfile = ""
default_bls_keyfile = "/Users/tymoteusz/.eigenlayer/operator_keys/testkey.bls.key.json"
default_ecdsa_address = "0x0000000000000000000000000000000000000000"
default_bls_address = "9759e20e9259f9090c7f4d2c28bd1119601000a31d4e308d918961d2012ae2e2cf5f9f5774d3e160505b236084924b53148ab6c543bb38a4fceeb68721204063e48121648426a3c7be35df5c23d72da3502160a4ab81d7b3533e656736b4ac58"

[metadata]
metadata_uri = ""
logo_uri = ""
favicon_uri = ""
