---
- name: Add Docker Module Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: true

- name: Install packages (for rust and docker)
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - python3-pip
      #    - rustc
      #    - cargo
      #    - protobuf-compiler
      #    - pkg-config
      #    - libssl-dev
      #    - docker-ce
      #    - docker-ce-cli
      #    - containerd.io
      #    - docker-buildx-plugin
      #    - docker-compose-plugin
      #
      #

- name: Install githbub3.py (for github access)
  ansible.builtin.pip:
    name: github3.py
    state: latest
    break_system_packages: true

- name: Prepare directories
  ansible.builtin.file:
    path: "{{ ivynet_client_install_path }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: true
  loop:
    - bin
    - resources

- name: Download ivynet-cli
  ansible.builtin.include_tasks:
    file: get_ivynet.yml

- name: Download eigenlayer resources (cli, point files etc.)
  ansible.builtin.include_tasks:
    file: get_eigen.yml

- name: Upload MOTD
  ansible.builtin.template:
    src: motd.txt.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
