[package]
name = "ivy-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
confy = "0.6.1"
dialoguer = "0.11.0"
dirs = "5.0.1"
ethers-contract = "2.0.14"
ethers-core = "2.0.14"
ethers-middleware = "2.0.14"
ethers-providers = "2.0.14"
ethers-signers = "2.0.14"
eyre = "0.6.12"
hex = "0.4.3"
lazy_static = "1.4.0"
pem = "3.0.4"
secp256k1 = { version = "0.29.0", features = ["rand", "rand-std"] }
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"
sha3 = "0.10.8"
tokio = { version = "1.37.0", features = ["full"] }
url = "2.5.0"


# [workspace.lints.clippy]
# # Duplicated from Reth - Reth has more enabled but lists them as experimental so
# # we're not enabling them here.
# #
# # These are some of clippy's nursery (i.e., experimental) lints that we like.
# # By default, nursery lints are allowed. Some of the lints below have made good
# # suggestions which we fixed. The others didn't have any findings, so we can
# # assume they don't have that many false positives. Let's enable them to
# # prevent future problems.
# branches_sharing_code = "warn"
# clear_with_drain = "warn"
# derive_partial_eq_without_eq = "warn"
# empty_line_after_outer_attr = "warn"
# equatable_if_let = "warn"
# imprecise_flops = "warn"
# iter_on_empty_collections = "warn"
# iter_with_drain = "warn"
# large_stack_frames = "warn"
# manual_clamp = "warn"
# mutex_integer = "warn"
# needless_pass_by_ref_mut = "warn"
# nonstandard_macro_braces = "warn"
# or_fun_call = "warn"
# path_buf_push_overwrite = "warn"
# read_zero_byte_vec = "warn"
# redundant_clone = "warn"
# suboptimal_flops = "warn"
# suspicious_operation_groupings = "warn"
# trailing_empty_array = "warn"
# trait_duplication_in_bounds = "warn"
# transmute_undefined_repr = "warn"
# trivial_regex = "warn"
# tuple_array_conversions = "warn"
# uninhabited_references = "warn"
# unused_peekable = "warn"
# unused_rounding = "warn"
# useless_let_if_seq = "warn"
