---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      tags: github
  pre_tasks:
    - name: Install extra packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - git
        - python3-debian
