path = "/home/tymek/fixes/ivynet/cli/test_create_key"
key_path = "/home/tymek/fixes/ivynet/cli/test_create_key"
mainnet_rpc_url = "https://rpc.flashbots.net/fast"
holesky_rpc_url = "https://eth-holesky.public.blastapi.io"
local_rpc_url = "http://localhost:8545"
default_ecdsa_keyfile = "/home/tymek/fixes/ivynet/cli/test_create_key/testkey.ecdsa.json"
default_bls_keyfile = ""
default_ecdsa_address = "0x3c289f526579da5fbc12cc84b8b45a54bc051c02"
default_bls_address = ""

[metadata]
metadata_uri = ""
logo_uri = ""
favicon_uri = ""
