[package]
name = "ivynet-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["http2", "macros", "multipart"] }
clap = { version = "4.5", features = ["derive", "env"] }
ivynet-core = { path = "../core/" }
prost = "0.12"
prost-wkt = "0.5"
prost-wkt-types = "0.5"
serde = { version = "1.0", features = ["derive"]}
sqlx = { version = "0.7", features = ["postgres", "chrono", "runtime-tokio", "tls-rustls", "uuid"] }
thiserror = "1.0"
tokio = { version = "1.38", features = ["full", "sync", "rt", "macros", "rt-multi-thread"] }
tower = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3.18"
url = { version = "2.5.1", features = ["serde"] }
tonic = { version = "0.12", features = ["tls"] }
tonic-reflection = { version = "0.11" }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
chrono = "0.4"
sha256 = "1.5"
memcache = "0.17.2"
axum-extra = { version = "0.9.3", features = ["cookie"] }
sendgrid = "0.21.0"
utoipa = { version = "4.2.3", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }
