---
services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - psql_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ivy
      POSTGRES_PASSWORD: secret_ivy
      POSTGRES_DB: ivynet
    healthcheck:
      test: pg_isready -U ivy -d ivynet
      interval: 10s
      timeout: 3s
      retries: 3

  memcached:
    container_name: memcached
    image: 'memcached:alpine'
    ports:
      - 11211:11211
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211
      interval: 10s
      timeout: 3s
      retries: 60

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTEXT_APK=ivynet-backend
    environment:
      DATABASE_URL: postgresql://ivy:secret_ivy@postgres:5432/ivynet
      IVY_CACHE_URL: memcache://memcached:11211
      IVY_MIGRATE: "true"
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_ORG_VER_TMP: ${SENDGRID_ORG_VER_TMP}
      SENDGRID_USER_VER_TMP: ${SENDGRID_USER_VER_TMP}
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_healthy
    ports:
      - "50050:50050"
      - "8080:8080"

volumes:
  psql_vol:
