---
- name: Reload daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart ingress service
  ansible.builtin.systemd_service:
    name: ivynet-ingress
    state: restarted
    enabled: true
