[package]
name = "cli"
version = "0.1.0"
edition = "2021"
authors = ["Noah Foltz <noah@ivynet.dev>"]
description = "CLI for Ivynet client"
keywords = ["cli", "tool"]
repository = "https://github.com/ivy-net/ivynet"
default-run = "ivynet"
license = "UNLICENSED"

[[bin]]
name = "ivynet"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.7", features = ["derive", "env"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ivynet-core = { path = "../core" }
thiserror = "1.0"
dialoguer = "0.11.0"
toml = "0.8.15"
reqwest = "0.12.5"
serde_json = "1.0"
hex = "0.4"
blsful = "2.5.7"
scrypt = "0.11.0"
rand = "0.8"
aes = "0.8.4"
sha2 = "0.10"
ctr = "0.9"
