[package]
name = "cli"
version = "0.1.9"
edition = "2021"
authors = ["Noah Foltz <noah@ivynet.dev>"]
description = "CLI for Ivynet client"
keywords = ["cli", "tool"]
repository = "https://github.com/ivy-net/ivynet"
default-run = "ivynet"
license = "UNLICENSED"

[[bin]]
name = "ivynet"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.7", features = ["derive", "env"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ivynet-core = { path = "../core" }
thiserror = "1.0"
dialoguer = "0.11.0"
reqwest = "0.12.5"
anyhow = "1.0.86"
linemux = "=0.3.0"
rustix = { version = "0.38", default-features = false, features = ["system"] }
data-encoding = "2.6.0"
