[package]
name = "ivynet-docker"
version = "0.4.4"
edition = "2021"
authors = ["Noah Foltz <noah@ivynet.dev>", "Phil Mulliken <phil@ivynet.dev>"]
description = "Docker library for IvyNet node detection and management"
repository = "https://github.com/ivy-net/ivynet"
license = "UNLICENSED"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
bollard.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
which.workspace = true
