---
- name: Get release id
  ansible.builtin.uri:
    # yamllint disable-line rule:line-length
    url: "https://api.github.com/repos/ivy-net/ivynet/releases/tags/ingress-{{ ivynet_ingress_release }}"
    method: GET
    headers:
      Authorization: "token {{ ivynet_ingress_github_token }}"
    follow_redirects: all
  register: ivynet_ingress_assets_output
  tags:
    - ivynet_ingress
    - ivynet
    - github

- name: Prepare variable with ingress assets id
  ansible.builtin.set_fact:
    # yamllint disable-line rule:line-length
    ivynet_ingress_assets_id: "{{ ivynet_ingress_assets_output | community.general.json_query(json_output_query) }}"
    cacheable: true
  vars:
    json_output_query: "json.assets[?name=='ivynet-ingress'].id"
  tags:
    - ivynet_ingress
    - ivynet
    - github

- name: Get binaries
  ansible.builtin.uri:
    # yamllint disable-line rule:line-length
    url: "https://api.github.com/repos/ivy-net/ivynet/releases/assets/{{ ivynet_ingress_assets_id[0] }}"
    method: GET
    headers:
      Authorization: "token {{ ivynet_ingress_github_token }}"
      Accept: "application/octet-stream"
    follow_redirects: all
    status_code: [200, 304]
    dest: "{{ ivynet_ingress_path_install }}/bin/ivynet-ingress"
    owner: root
    group: root
    mode: "0755"
  tags:
    - ivynet_ingress
    - ivynet
    - github

- name: Save ivynet release info
  ansible.builtin.copy:
    # yamllint disable-line rule:line-length
    dest: "{{ ivynet_ingress_path_install }}/ingress-{{ ivynet_ingress_release }}"
    content: |
      ingress-{{ ivynet_ingress_release }}
    owner: root
    group: root
    mode: "0444"
  notify: Restart ingress service
  tags:
    - ivynet_ingress
    - ivynet
    - github
    - systemd

- name: Add another bin dir to system-wide $PATH.
  ansible.builtin.copy:
    dest: /etc/profile.d/ivy-path.sh
    content: 'PATH=$PATH:{{ ivynet_ingress_path_install }}/bin'
    owner: root
    group: root
    mode: "0644"
  tags:
    - ivynet
