---
- name: Prepare directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ ivynet_ingress_path_install }}"
    - "{{ ivynet_ingress_path_install }}/bin"
    - "{{ ivynet_ingress_path_resources }}"
  tags:
    - general

- name: Set secrets directory
  ansible.builtin.file:
    path: "{{ ivynet_ingress_path_secrets }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags:
    - general
    - ssl

- name: Download ivynet-ingress for master
  ansible.builtin.import_tasks:
    file: get_ingress_master.yml
  when:
    - not ivynet_ingress_is_release

- name: Download ivynet-ingress for release
  ansible.builtin.import_tasks:
    file: get_ingress.yml
  when:
    - ivynet_ingress_is_release

# I need to readd it somehow
#- name: Copy Env file
#  ansible.builtin.template:
#    src: env.j2
#    dest: "{{ ivynet_ingress_path_secrets }}/env"
#    owner: root
#    group: root
#    mode: "0600"
#  notify:
#    - Restart ingress service
#  tags:
#    - general
#    - ivynet
#    - systemd
#    - template

- name: Configure SSL
  ansible.builtin.import_tasks:
    file: ssl.yml

- name: Copy Ingress Service file
  ansible.builtin.template:
    src: ivynet-ingress.service.j2
    dest: /etc/systemd/system/ivynet-ingress.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload daemon
    - Restart ingress service
  tags:
    - ivynet_ingress
    - general
    - ivynet
    - systemd
    - template

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Set Ingress service
  ansible.builtin.systemd_service:
    name: ivynet-ingress
    state: started
    enabled: true
    daemon_reload: true
  when:
    - "'ivynet-ingress.service' not in services"
  tags:
    - ivynet_ingress
    - general
    - ivynet
    - systemd
