---
- name: Get Checksum of the file
  ansible.builtin.stat:
    path: "{{ witness_chain_path_op }}/data/{{ witness_chain_arch_file }}"
    checksum_algorithm: sha256
    get_checksum: true
  register: arch_file
  vars:
    ansible_command_timeout: 1200
  tags:
    - general
    - big_file
    - download

- name: Download archive
  ansible.builtin.get_url:
    url: "{{ witness_chain_arch_url }}"
    dest: "{{ witness_chain_path_op }}/data"
    checksum: "sha256:{{ witness_chain_arch_checksum }}"
    owner: root
    group: root
    mode: "0644"
  vars:
    ansible_command_timeout: 3600
  when: not arch_file.stat.exists or
    witness_chain_arch_checksum != arch_file.stat.checksum
  tags:
    - witness_chain
    - big_file
    - download

- name: Untar the file
  ansible.builtin.unarchive:
    src: "{{ witness_chain_path_op }}/{{ witness_chain_arch_file }}"
    dest: "{{ witness_chain_path_op }}/data"
    remote_src: true
  tags:
    - witness_chain
    - big_file
