---
- name: Add Docker Module Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    # yamllint disable-line rule:line-length
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: true
  tags:
    - witness_chain
    - general
    - docker

- name: Add Go Lang Repository
  ansible.builtin.apt_repository:
    repo: "ppa:longsleep/golang-backports"
    state: present
  tags:
    - witness_chain
    - general
    - golang

- name: Install packages (for rust and docker)
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - python3-pip
    - rustc
    - cargo
    - protobuf-compiler
    - pkg-config
    - libssl-dev
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - npm
    - golang
  tags:
    - witness_chain
    - general
    - docker
    - download

#- name: Install pnpm
#  community.general.npm:
#    name: pnpm
#    global: true
#  tags:
#    - witness_chain
#    - general
#    - docker
#    - download

- name: Prepare directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ witness_chain_path_ivynet }}"
    - "{{ witness_chain_path_ivynet }}/bin"
    - "{{ witness_chain_path_op }}"
    - "{{ witness_chain_path_op }}/data"
  tags:
    - witness_chain
    - general

- name: Get Checksum of the file
  ansible.builtin.stat:
    path: "{{ witness_chain_path_op }}/data/{{ witness_chain_arch_file }}"
    checksum_algorithm: sha256
    get_checksum: true
  register: arch_file
  vars:
    ansible_command_timeout: 1200
  tags:
    - general
    - big_file
    - download

- name: Download archive
  ansible.builtin.get_url:
    url: "{{ witness_chain_arch_url }}"
    dest: "{{ witness_chain_path_op }}/data"
    checksum: "sha256:{{ witness_chain_arch_checksum }}"
    owner: root
    group: root
    mode: "0644"
  vars:
    ansible_command_timeout: 3600
  when: not arch_file.stat.exists or
    witness_chain_arch_checksum != arch_file.stat.checksum
  tags:
    - witness_chain
    - big_file
    - download

- name: Untar the file
  ansible.builtin.unarchive:
    src: "{{ witness_chain_path_op }}/{{ witness_chain_arch_file }}"
    dest: "{{ witness_chain_path_op }}/data"
    remote_src: true
  tags:
    - witness_chain
    - big_file

- name: Install Optimism node
  ansible.builtin.import_tasks:
    file: make_op_node.yml

- name: Install Optimism node
  ansible.builtin.import_tasks:
    file: make_op_geth.yml

- name: Create JWT file
  ansible.builtin.copy:
    # yamllint disable-line rule:line-length
    content: "0{{ query('ansible.builtin.password', chars=hex_chars, length=32, seed=inventory_hostname) }}"
    dest: "{{ witness_chain_path_op }}/jwt.txt"
    owner: root
    group: root
    mode: "0644"
  vars:
    hex_chars: '0123456789ABCDEF'
  tags:
    - witness_chain
    - general
