[package]
name = "ivynet-core"
version = "0.1.0"
edition = "2021"
authors = ["Noah Foltz <noah@ivynet.dev>"]
description = "Core library for Ivynet client functionality"
repository = "https://github.com/ivy-net/ivynet"
license = "UNLICENSED"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

# TODO: Remove clap as a dependency unless cli-feature is enabled
[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
futures-util = "0.3"
dialoguer = "0.11.0"
dirs = "5.0.1"
dotenvy = "0.15.7"
ethers = "2.0"
indicatif = "0.17.8"
once_cell = "1.19.0"
regex = "1.10.6"
reqwest = { version = "0.12", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
serde_yaml = "0.9.34"
sysinfo = "0.30.11"
thiserror = "1.0.62"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.15"
tracing = "0.1.40"
zip = "2.1.3"
url = { version = "2.5.1", features = ["serde"] }
chrono = "0.4"
async-trait = "0.1.80"
ivynet-macros = { path = "../macros" }
blsful = "2.5.7"
rand = "0.8"

#grpc
prost = "0.12"
prost-wkt = "0.5"
prost-wkt-types = "0.5"
tonic = { version = "0.11", features = ["tls", "tls-roots"] }
tonic-reflection = "0.11"
tokio-stream = { version = "0.1.15", features = ["net"] }
tower = "0.4.13"
hyper-util = { version = "0.1.6", features = ["full", "tokio"] }
which = "6.0.2"
eth-keystore = { version = "0.5.0", features = ["geth-compat"] }

[build-dependencies]
prost-build = "0.12"
prost-wkt-build = "0.5"
tonic-build = "0.11"

[dev-dependencies]
tempfile = "3.10.1"


[package.metadata.cargo-machete]
ignored = ["chrono", "prost", "prost-wkt", "prost-wkt-types"]
