---
- name: Get binaries from GCP
  google.cloud.gcp_storage_object:
    auth_kind: serviceaccount
    bucket: "{{ ivynet_client_gcp_bucket }}"
    src: "ivy-master/{{ item }}"
    dest: "/tmp/{{ item }}"
    action: download
    service_account_file: "{{ ivynet_client_gcp_cred }}"
    project: "{{ ivynet_client_gcp_project }}"
  delegate_to: localhost
  become: false
  loop:
    - ivynet
  tags:
    - download
    - gcp

- name: Upload binaries
  ansible.builtin.copy:
    src: "/tmp/{{ item }}"
    dest: "{{ ivynet_client_path_bin }}/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - ivynet
  tags:
    - download
    - gcp

- name: Install extra software
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - expect
  tags:
    download

- name: Upload scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ivynet_client_path_bin }}/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - reset_ivynet.sh
  tags:
    - download

- name: Upload config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ivynet_client_path_resources }}/{{ item }}"
    owner: "{{ ivynet_client_user }}"
    group: "{{ ivynet_client_group }}"
    mode: "0644"
  loop:
    - monitor-conf.toml
  tags:
    - config
    - download

- name: Upload scripts (from template)
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ivynet_client_path_bin }}/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - reset_ivynet.exp
    - master_reset.sh
  tags:
    - download
