---
- name: Get latest release of ivynet-client
  community.general.github_release:
    user: ivy-net
    repo: ivynet
    token: "{{ ivynet_client_github_token }}"
    action: latest_release
  register: ivynet_client_release
  tags:
    - github

- name: Expose tag of the downloaded assets
  ansible.builtin.debug:
    msg: "{{ ivynet_client_release.tag }} is the tag"
  tags:
    - github

- name: Get release id
  ansible.builtin.uri:
    # yamllint disable-line rule:line-length
    url: "https://api.github.com/repos/ivy-net/ivynet/releases/tags/{{ ivynet_client_release.tag }}"
    method: GET
    headers:
      Authorization: "token {{ ivynet_client_github_token }}"
    follow_redirects: all
  register: ivynet_client_assets_output
  tags:
    - github

- name: Prepare variable if assets id
  ansible.builtin.set_fact:
    # yamllint disable-line rule:line-length
    ivynet_client_assets_id: "{{ ivynet_client_assets_output | community.general.json_query(json_output_query) }}"
    cacheable: true
  vars:
    json_output_query: "json.assets[?name=='ivynet'].id"
  tags:
    - github

- name: Get asset
  ansible.builtin.uri:
    # yamllint disable-line rule:line-length
    url: "https://api.github.com/repos/ivy-net/ivynet/releases/assets/{{ ivynet_client_assets_id[0] }}"
    method: GET
    headers:
      Authorization: "token {{ ivynet_client_github_token }}"
      Accept: "application/octet-stream"
    follow_redirects: all
    status_code: [200, 304]
    dest: "{{ ivynet_client_path_install }}/bin/ivynet"
    owner: ivynet
    group: root
    mode: "0755"
  tags:
    - github

- name: Save ivynet release info
  ansible.builtin.copy:
    dest: "{{ ivynet_client_path_install }}/ivynet.tag"
    content: |
      {{ ivynet_client_release.tag }}
    owner: ivynet
    group: root
    mode: "0444"
  tags:
    - github
