---
- name: Add user ivynet
  ansible.builtin.user:
    name: ivynet
    comment: Ivynet Client user
    groups: docker
    create_home: true
    shell: /bin/false
  tags:
    - ivnet_client
    - ivynet_user
    - systemd

- name: Prepare directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: ivynet
    group: root
    mode: "0755"
  loop:
    - "{{ ivynet_client_path_install }}"
    - "{{ ivynet_client_path_install }}/bin"
    - "{{ ivynet_client_path_resources }}"
  tags:
    - ivynet_client

- name: Add ivynet bin dir to system-wide $PATH.
  ansible.builtin.copy:
    dest: /etc/profile.d/ivy-path.sh
    content: "PATH=$PATH:{{ ivynet_client_path_install }}/bin"
    owner: root
    group: root
    mode: "0644"
  tags:
    - ivynet_client

- name: Install and configure 3rd party tools
  ansible.builtin.import_tasks:
    file: third_party.yml

- name: Download ivynet-cli
  ansible.builtin.import_tasks:
    file: get_ivynet.yml

- name: Setup systemd
  ansible.builtin.import_tasks:
    file: systemd.yml
  when:
    - ivynet_client_systemd

- name: Upload MOTD
  ansible.builtin.template:
    src: motd.txt.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  tags:
    - ivynet_client
    - template

- name: Download eigenlayer resources (cli, point files etc.)
  ansible.builtin.import_tasks:
    file: get_eigen.yml
  when:
    - ivynet_client_eigenda
