---
- name: Prepare directories
  ansible.builtin.file:
    path: "{{ ivynet_client_path_install }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - ''
    - bin
    - resources
  tags:
    - ivynet_client
    - general

- name: Download third party tools (rust, docker)
  ansible.builtin.import_tasks:
    file: third_party.yml

- name: Download ivynet-cli
  ansible.builtin.import_tasks:
    file: get_ivynet.yml

- name: Upload MOTD
  ansible.builtin.template:
    src: motd.txt.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  tags:
    - ivynet_client
    - general

- name: Copy Backend Service file
  ansible.builtin.template:
    src: ivynet-client.service.j2
    dest: /etc/systemd/system/ivynet-client.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload daemon
    - Restart client service
  tags:
    - ivynet_client
    - general
    - ivynet
    - systemd
    - template

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Set Backend service
  ansible.builtin.systemd_service:
    name: ivynet-client
    state: started
    enabled: true
    daemon_reload: true
  when:
    - "'ivynet-client.service' not in services"
  tags:
    - ivynet_client
    - general
    - ivynet
    - systemd

- name: Add ivynet bin dir to system-wide $PATH.
  ansible.builtin.copy:
    dest: /etc/profile.d/ivy-path.sh
    content: "PATH=$PATH:{{ ivynet_client_path_install }}/bin"
    owner: root
    group: root
    mode: "0644"
  tags:
    - ivynet_client
    - ivynet

- name: Download eigenlayer resources (cli, point files etc.)
  ansible.builtin.import_tasks:
    file: get_eigen.yml
  when:
    - ivynet_client_eigenda
