---
- name: Prepare directories
  ansible.builtin.file:
    path: "{{ ivynet_client_install_path }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - ''
    - bin
    - resources
  tags:
    - general

- name: Download third party tools (rust, docker)
  ansible.builtin.import_tasks:
    file: third_party.yml

- name: Download ivynet-cli
  ansible.builtin.import_tasks:
    file: get_ivynet.yml

- name: Download eigenlayer resources (cli, point files etc.)
  ansible.builtin.import_tasks:
    file: get_eigen.yml

- name: Upload MOTD
  ansible.builtin.template:
    src: motd.txt.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  tags:
    - general

- name: Add ivynet bin dir to system-wide $PATH.
  ansible.builtin.copy:
    dest: /etc/profile.d/ivy-path.sh
    content: "PATH=$PATH:{{ ivynet_client_install_path }}/bin"
    owner: root
    group: root
    mode: "0644"
  tags:
    - ivynet
