---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  pre_tasks:
    - name: Install extra packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3-debian
      tags:
        - github
    - name: Info
      ansible.builtin.debug:
        msg: "Finish pre tasks"
      tags:
        - github
