---
- hosts: gcp_area_backend:&gcp_env_gha
  pre_tasks:
    - name: Use GCloud
      ansible.builtin.command: |
        gcloud sql instances list
        --filter="name:{{ ansible_hostname }}"
        --format="json(ipAddresses)"
      register: db_info
      delegate_to: localhost
      changed_when: false
    - name: print IP
      ansible.builtin.set_fact:
        db_ip: "{{ (db_info.stdout | from_yaml )[0].ipAddresses[0].ipAddress }}"
  roles:
    - role: ivynet-api
      ivynet_api_postgres_host: "{{ db_ip }}"
      become: true
    - role: ivynet-ingress
      ivynet_ingress_postgres_host: "{{ db_ip }}"
      become: true
    - role: ivynet-scanner
      become: true
