---
- hosts: api1
  pre_tasks:
    - name: Use GCloud
      ansible.builtin.command: |
        gcloud sql instances list
        --filter="name:{{ ansible_hostname }}"
        --format="json(ipAddresses)"
      register: db_info
      delegate_to: localhost
    - name: print IP
      ansible.builtin.set_fact:
        db_ip: "{{ (db_info.stdout | from_yaml )[0].ipAddresses[0].ipAddress }}"
  roles:
    - role: ivynet-backend
      ivynet_backend_postgres_host: "{{ db_ip }}"
      become: true
    - role: ivynet-scraper
      become: true
