---
- hosts: gcp_area_backend:&gcp_env_dev
  roles:
    - role: ivynet-api
      ivynet_api_is_release: false
      ivynet_api_site_url: https://dev.ivynet.dev
      become: true
    - role: ivynet-ingress
      ivynet_ingress_is_release: false
      become: true
    - role: ivynet-scraper
      ivynet_scraper_is_release: false
      become: true
