---
- hosts: default
  become: true
  pre-tasks:
    - name: Remove system cargo
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop:
        - cargo
        - rustc
    - name: Install external rust
      ansible.builtin.shell:
        cmd: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  roles:
    - ivynet-backend
