---
- hosts: default
  pre_tasks:
    - name: Remove system cargo
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop:
        - cargo
        - rustc
      become: true
    - name: Install external rust
      ansible.builtin.shell:
        cmd: >
          curl
          --proto '=https'
          --tlsv1.2
          -sSf
          https://sh.rustup.rs
          | sh -s -- -y
      become: true
  roles:
    - role: ivynet-backend
      become: true
    - role: ivynet-ingress
      become: true
    - role: ivynet-scraper
      become: true
