---
- hosts: gcp_area_backend:&gcp_env_dev
  roles:
    - role: ivynet-backend
      ivynet_backend_is_release: false
      become: true
    - role: ivynet-ingress
      ivynet_ingress_is_release: false
      become: true
    - role: ivynet-scraper
      ivynet_scraper_is_release: false
      become: true
