---
plugin: google.cloud.gcp_compute
projects:
  - ivynet-tests
filters:
  - status = RUNNING
  - scheduling.automaticRestart = true AND status = RUNNING
service_account_file: ~/.devops-automation-key.json
auth_kind: serviceaccount
scopes:
  - 'https://www.googleapis.com/auth/cloud-platform'
  - 'https://www.googleapis.com/auth/compute.readonly'
keyed_groups:
  - prefix: gcp
    key: labels
hostnames:
  - name
  - public_ip
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
