---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine.prv
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  pre_tasks:
    - name: Install extra packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3-debian
        - python3-pip
      tags:
        - github
    - name: Info
      ansible.builtin.debug:
        msg: "Finish pre tasks"
      tags:
        - github
