---
driver:
  name: gce
  project_id: ivynet-tests
  region: us-central1
  instance_os_type: linux
  external_access: true
  auth_kind: serviceaccount
  service_account_file: ~/Downloads/ivynet-tests-ceea81669ebb.json
  # auth_kind: machineaccount
  # service_account_email: 364175035760-compute@developer.gserviceaccount.com
  username: ubuntu
  credentials_file: ~/.ssh/google_compute_engine
platforms:
  - name: molecule-cloudstation
    image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2404-lts-amd64'
