---
- name: Get release id
  ansible.builtin.uri:
    # yamllint disable-line rule:line-length
    url: "https://api.github.com/repos/ivy-net/ivynet/releases/tags/backend-{{ ivynet_backend_release }}"
    method: GET
    headers:
      Authorization: "token {{ ivynet_backend_github_token }}"
    follow_redirects: all
  register: ivynet_backend_assets_output
  tags:
    - ivynet_backend
    - github

- name: Prepare variable with backend assets id
  ansible.builtin.set_fact:
    # yamllint disable-line rule:line-length
    ivynet_backend_assets_id: "{{ ivynet_backend_assets_output | community.general.json_query(json_output_query) }}"
    cacheable: true
  vars:
    json_output_query: "json.assets[?name=='ivynet-backend'].id"
  tags:
    - ivynet_backend
    - github

- name: Get binaries
  ansible.builtin.uri:
    # yamllint disable-line rule:line-length
    url: "https://api.github.com/repos/ivy-net/ivynet/releases/assets/{{ ivynet_backend_assets_id[0] }}"
    method: GET
    headers:
      Authorization: "token {{ ivynet_backend_github_token }}"
      Accept: "application/octet-stream"
    follow_redirects: all
    status_code: [200, 304]
    dest: "{{ ivynet_backend_path_install }}/bin/ivynet-backend"
    owner: root
    group: root
    mode: "0755"
  tags:
    - ivynet_backend
    - github

- name: Save ivynet release info
  ansible.builtin.copy:
    # yamllint disable-line rule:line-length
    dest: "{{ ivynet_backend_path_install }}/backend-{{ ivynet_backend_release }}"
    content: |
      backend-{{ ivynet_backend_release }}
    owner: root
    group: root
    mode: "0444"
  notify: Restart backend service
  tags:
    - ivynet_backend
    - github
    - systemd
