---
- name: Copy logs cleaner script
  ansible.builtin.copy:
    src: logs-cleaner.sh
    dest: "{{ ivynet_backend_path_install }}/bin"
    owner: root
    group: root
    mode: "0755"
  tags:
    - ivynet_backend
    - general
    - ivynet
    - db

- name: Clean logs table
  ansible.builtin.cron:
    name: "Clean logs table"
    minute: 30
    hour: "1,13"
    # yamllint disable-line rule:line-length
    job: "{{ ivynet_backend_path_install }}/bin/logs-cleaner.sh 2>&1 |logger -t logs-clener"
  tags:
    - ivynet_backend
    - general
    - ivynet
    - db

- name: Copy scanner script
  ansible.builtin.copy:
    src: ivynet-scanner.sh
    dest: "{{ ivynet_backend_path_install }}/bin"
    owner: root
    group: root
    mode: "0755"
  tags:
    - ivynet_backend
    - general
    - ivynet
    - scanner

- name: Run scanner from the cron
  ansible.builtin.cron:
    name: "Run image version scanner"
    minute: 7
    hour: "0,12"
    # yamllint disable-line rule:line-length
    job: "{{ ivynet_backend_path_install }}/bin/ivynet-scanner.sh 2>&1 |logger -t scanner"
  tags:
    - ivynet_backend
    - general
    - ivynet
    - scanner
