---
- name: Setup config
  ansible.builtin.template:
    src: nginx-backend.conf.j2
    dest: /etc/nginx/sites-available/backend.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload Nginx
  tags:
    - nginx
    - systemd
