---
- name: Get repo (for migration files)
  ansible.builtin.git:  # noqa: latest[git]
# yamllint disable-line rule:line-length
    repo: "https://{{ ivynet_backend_github_token }}@github.com/ivy-net/ivynet.git"
    dest: "{{ ivynet_backend_path_install }}/repo"
  tags:
    - ivynet
    - db-config

- name: Configure postgres DB for ivynet
  community.postgresql.postgresql_db:
    name: ivynet
  become: true
  become_user: postgres
  tags:
    - ivynet
    - postgres
    - db-config

- name: Add postgres ivy user
  community.postgresql.postgresql_user:
    name: "{{ ivynet_backend_postgres_user }}"
    password: "{{ ivynet_backend_postgres_pass }}"
  become: true
  become_user: postgres
  tags:
    - ivynet
    - postgres
    - db-config

- name: Add privilges to the user
  community.postgresql.postgresql_privs:
    database: "{{ ivynet_backend_postgres_db }}"
    privs: ALL
    type: schema
    objs: public
    role: "{{ ivynet_backend_postgres_user }}"
  become: true
  become_user: postgres
  tags:
    - ivynet
    - postgres
    - db-config

- name: Run migrations
  ansible.builtin.command:
    cmd: >
      {{ ivynet_backend_path_install }}/bin/sqlx
      migrate
      run
      --database-url
      postgresql://{{ ivynet_backend_postgres_user }}:{{ ivynet_backend_postgres_pass }}@localhost:5432/{{ ivynet_backend_postgres_db }}
    chdir: "{{ ivynet_backend_path_resources }}"
  register: migration_out
  changed_when: migration_out.stdout != ""
  tags:
    - ivynet
    - db-config
    - sqlx
