---
- name: Get release id
  ansible.builtin.uri:
    # yamllint disable-line rule:line-length
    url: "https://api.github.com/repos/ivy-net/ivynet/releases/tags/api-{{ ivynet_api_release }}"
    method: GET
    headers:
      Authorization: "token {{ ivynet_api_github_token }}"
    follow_redirects: all
  register: ivynet_api_assets_output
  tags:
    - ivynet_api
    - github

- name: Prepare variable with api assets id
  ansible.builtin.set_fact:
    # yamllint disable-line rule:line-length
    ivynet_api_assets_id: "{{ ivynet_api_assets_output | community.general.json_query(json_output_query) }}"
    cacheable: true
  vars:
    json_output_query: "json.assets[?name=='ivynet-api'].id"
  tags:
    - ivynet_api
    - github

- name: Get binaries
  ansible.builtin.uri:
    # yamllint disable-line rule:line-length
    url: "https://api.github.com/repos/ivy-net/ivynet/releases/assets/{{ ivynet_api_assets_id[0] }}"
    method: GET
    headers:
      Authorization: "token {{ ivynet_api_github_token }}"
      Accept: "application/octet-stream"
    follow_redirects: all
    status_code: [200, 304]
    dest: "{{ ivynet_api_path_install }}/bin/ivynet-api"
    owner: root
    group: root
    mode: "0755"
  tags:
    - ivynet_api
    - github

- name: Save ivynet release info
  ansible.builtin.copy:
    # yamllint disable-line rule:line-length
    dest: "{{ ivynet_api_path_install }}/api-{{ ivynet_api_release }}"
    content: |
      api-{{ ivynet_api_release }}
    owner: root
    group: root
    mode: "0444"
  notify: Restart api service
  tags:
    - ivynet_api
    - github
    - systemd
