---
- name: Get binaries from GCP
  google.cloud.gcp_storage_object:
    auth_kind: serviceaccount
    bucket: "{{ ivynet_api_gcp_bucket }}"
    src: "ivy-master/{{ item }}"
    dest: "/tmp/{{ item }}"
    action: download
    service_account_file: "{{ ivynet_api_gcp_cred }}"
    project: "{{ ivynet_api_gcp_project }}"
  delegate_to: localhost
  become: false
  loop:
    - ivynet-api
  tags:
    - ivynet_api
    - ivynet
    - download
    - gcp

- name: Upload binaries
  ansible.builtin.copy:
    src: "/tmp/{{ item }}"
    dest: "{{ ivynet_api_path_install }}/bin/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - ivynet-api
  notify: Restart api service
  tags:
    - ivynet_api
    - ivynet
    - download
    - gcp
