---
- name: Copy API Service file
  ansible.builtin.template:
    src: ivynet-api.service.j2
    dest: /etc/systemd/system/ivynet-api.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload daemon
    - Restart api service
  tags:
    - ivynet_api
    - general
    - systemd
    - template

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Set API service
  ansible.builtin.systemd_service:
    name: ivynet-api
    state: started
    enabled: true
    daemon_reload: true
  when:
    - "'ivynet-api.service' not in services"
  tags:
    - ivynet_api
    - general
    - systemd
