[[configured_avses]]
assigned_name = "EigenDA"
container_name = "eigenda-native-node"
avs_type = "eigen-da"
metric_port = 9092
manifest = "932da7c79db6881554d9dae9628484c8e3f675dc5ccedf2f5a8039cd28db828f"

[configured_avses.image]
repository = "ghcr.io/layr-labs/eigenda/opr-node"
tag = "0.9.0-rc.0"

[[configured_avses]]
assigned_name = "Ava"
container_name = "ap_operator"
avs_type = "ava-protocol"
metric_port = 9290
manifest = "c43d39f4d09f5ffb97ee8d614a236955e1359ea548871da1a32d75016f531938"

[configured_avses.image]
repository = "avaprotocol/ap-avs"
tag = "1.5.0"
