services:
  fluentd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluentd
    volumes:
      - ${FLUENTD_PATH}/conf:/fluentd/etc
      - ${FLUENTD_PATH}/log:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
