---
- name: Reload daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart api service
  ansible.builtin.systemd_service:
    name: ivynet-api
    state: restarted
    enabled: true
