---
name: Build and Tag on Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:

  build:
    name: Build everything
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          sudo apt install
          protobuf-compiler
          pkg-config
          libssl-dev
      - name: Install official Rust
        run: >
          curl
          --proto '=https'
          --tlsv1.2
          -sSf
          https://sh.rustup.rs
          |
          sh -s -- -y
      - name: Build binaries
        run: |
          . "$HOME/.cargo/env"
          cargo build --release


  tag-backend:
    name: Tag backend
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install official Rust
        run: >
          curl
          --proto '=https'
          --tlsv1.2
          -sSf
          https://sh.rustup.rs
          |
          sh -s -- -y
      - name: Install TOML cli
        run: |
          . "$HOME/.cargo/env"
          cargo install toml-cli
          echo "path: $PATH"
      - name: Extract TOML version
        id: version-backend
        run: |
          version=$(toml get backend/Cargo.toml package.version)
          echo "TAG_BACKEND_TOML=${version}" >> "$GITHUB_ENV"
      - name: Get latest git tag
        id: tag-backend
        run: |
          tag=$(git tag | awk -F- '/backend/ {print $2}')
          echo "TAG_BACKEND_GIT=${tag}" >> "$GITHUB_ENV"
      - name: Create new git tag
        if: >
          ${TAG_BACKEND_GIT}
          !=
          ${TAG_BACKEND_TOML}
        run: |
          git tag -f backend-${{ steps.version-backend.outputs.version }}
          git push origin backend-${{ steps.version-backend.outputs.version }}
          git tag -f client-${TAG_BACKEND_TOML}
          git push origin client-${TAG_BACKEND_TOML}

  tag-cli:
    name: Tag client
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install official Rust
        run: >
          curl
          --proto '=https'
          --tlsv1.2
          -sSf
          https://sh.rustup.rs
          |
          sh -s -- -y
      - name: Install TOML cli
        run: |
          . "$HOME/.cargo/env"
          cargo install toml-cli
      - name: Extract TOML version
        id: version-cli
        run: |
          version=$(toml get cli/Cargo.toml package.version)
          echo "TAG_CLI_TOML=${version}" >> "$GITHUB_OUTPUT"
      - name: Get latest tag
        id: tag-cli
        run: |
          tag=$(git tag | awk -F- '/client/ {print $2}')
          echo "TAG_CLI_GIT=${tag}" >> "$GITHUB_OUTPUT"
      - name: Create git tag
        if: >
          steps.version-cli.outputs.TAG_CLI_TOML
          !=
          steps.tag-cli.outputs.TAG_CLI_GIT
        env:
          NEW_TAG: ${{ steps.version-cli.outputs.TAG_CLI_TOML }}
        run: |
          git tag -f client-${NEW_TAG}
          git push origin client-${NEW_TAG}
