---
name: build dev

on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - ivynet-backend
      - ivynet-cli

jobs:
  build:
    name: build everything
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y rustc cargo protobuf-compiler pkg-config libssl-dev
      - run: cd ivynet
      - run: cargo build --release
