---
name: DevOps test

on:
  push:
    branches-ignore:
      - dev
      - master
    paths:
      - .github/**
      - devops/**

jobs:
  devops-tests:
    name: Various tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install official Rust
        run: >
          curl
          --proto '=https'
          --tlsv1.2
          sSf
          https://sh.rustup.rs
          |
          sh -s -- -y
      - name: Install TOML cli
        run: |
          . "$HOME/.cargo/env"
          cargo install toml-cli
      - name: Extract TOML version
        id: version-cli
        run: |
          version=$(toml get cli/Cargo.toml package.version)
          echo "TAG_CLI=${version}" >> "$GITHUB_ENV"
      - name: Test version
        run: |
          echo "$TAG_CLI"
      - name: Test conditional
        if: >
          ${TAG_CLI_GIT}
          !=
          ${TAG_CLI_TOML}
        run: |
          echo -e "This is $TAG_CLI_ENV"
