---
name: DevOps test

on:
  push:
    branches-ignore:
      - dev
      - master
    paths:
      - .github/**
      - devops/**

jobs:
  devops-tests:
    name: Various tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get latest tag
        id: tag-backend
        run: |
          tag=$(git tag | awk -F- '/backend/ {print $2}'| tail -1)
          echo -e "Tag: ${tag}"
          echo "TAG_BACKEND_GIT=${tag}" >> "$GITHUB_OUTPUT"
      - name: Print version
        env:
          TAG: ${{ steps.tag-backend.outputs.TAG_BACKEND_GIT }}
        run: |
          echo -e "This is $TAG"
          echo -e "backend-$TAG"
      - name: Print version 2
        env:
          TAG: backend-${{ steps.tag-backend.outputs.TAG_BACKEND_GIT }}
        run: |
          echo -e "This is $TAG"
          echo -e "$TAG"
