---
name: DevOps test

on:
  push:
    branches-ignore:
      - dev
      - master
    paths:
      - .github/**
      - devops/**

jobs:
  devops-tests:
    name: Various tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install official Rust
        run: >
          curl
          --proto '=https'
          --tlsv1.2
          sSf
          https://sh.rustup.rs
          |
          sh -s -- -y
      - name: Install TOML cli
        run: |
          . "$HOME/.cargo/env"
          cargo install toml-cli
      - name: Test toml
        run: |
          echo -e "Normal PATH:"
          echo -e "$PATH"
          extra_path=$(echo "$PATH")
          echo -e "Inside PATH:"
          echo -e "$extra_path"
          echo -e "FULL PATH command:"
          $HOME/.cargo/bin/toml --help
          echo -e "FULL PATH INSIDE command:"
          hh=$($HOME/.cargo/bin/toml --help)
          echo -e "$hh"
          echo -e "SHORT PATH command:"
          toml --help
      - name: Extract TOML version
        id: version-cli
        run: |
          version=$(toml get cli/Cargo.toml package.version)
          echo "TAG_CLI=${version}" >> "$GITHUB_ENV"
      - name: Test version
        run: |
          echo "$TAG_CLI"
