---
name: DevOps test

on:
  push:
    branches-ignore:
      - dev
      - master
    paths:
      - .github/**
      - devops/**

jobs:
  devops-tests:
    name: Various tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get latest tag
        id: tag-cli
        run: |
          tag=$(git tag | awk -F- '/client/ {print $2}')
          echo "TAG_CLI_GIT=${tag}" >> "$GITHUB_OUTPUT"
      - name: Print version
        env:
          TAG_CLI: ${{ steps.tag-cli.outputs.TAG_CLI_GIT }}
        run: |
          echo -e "This is $TAG_CLI"
          echo -e "client-$TAG_CLI"
      - name: Print version 2
        env:
          TAG_CLI: client-${{ steps.tag-cli.outputs.TAG_CLI_GIT }}
        run: |
          echo -e "This is $TAG_CLI"
          echo -e "$TAG_CLI"
