---
name: DevOps test

on:
  push:
    branches-ignore:
      - dev
      - master
      - release-*
    paths:
      - .github/**
      - devops/**

jobs:
  devops-tests:
    name: Various tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.ED_25519 }}"
      - name: Get latest git tag
        id: tag-backend
        run: |
          git pull --tags
          tag=$(git tag | awk -F- '/backend/ {print $2}'| tail -1)
          echo "TAG_BACKEND_GIT=${tag}" >> "$GITHUB_OUTPUT"
          echo "Tag: ${tag}"
      - name: Debug
        run: |
          echo "${PATH}"
      - name: Install TOML cli
        run: |
          cd /usr/local/bin
          wget https://storage.googleapis.com/ivynet-share/toml
          chmod 0755 toml
          ls -l toml
      - name: Version backend
        id: version-backend
        run: |
          version=$(toml get backend/Cargo.toml package.version | tr -d \")
          echo "TAG_BACKEND_TOML=${version}" >> "$GITHUB_OUTPUT"
          echo "Version: ${version}"
