---
name: DevOps test

on:
  push:
    branches-ignore:
      - dev
      - master
    paths:
      - .github/**
      - devops/**

jobs:
  devops-tests:
    name: Various tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get version from TOML
        id: version-backend
        run: |
          version=$(toml get backend/Cargo.toml package.version | tr -d \")
          echo "TAG_BACKEND_TOML=${version}" >> "$GITHUB_ENV"
          echo "Version: ${version}"
      - name: Get latest git tag
        id: tag-backend
        run: |
          git pull --tags
          tag=$(git tag | awk -F- '/backend/ {print $2}'| tail -1)
          echo "TAG_BACKEND_GIT=${tag}" >> "$GITHUB_ENV"
          echo "Tag: ${tag}"
      - name: Print version GIT
        env:
          TAG: ${{ steps.tag-backend.outputs.TAG_BACKEND_GIT }}
        run: |
          echo -e "This is $TAG"
          echo -e "GIT: $TAG"
      - name: Print version TOML
        env:
          TAG: backend-${{ steps.tag-backend.outputs.TAG_BACKEND_TOML }}
        run: |
          echo -e "This is $TAG"
          echo -e "TOML: $TAG"
