---
name: DevOps test

on:
  push:
    branches:
      - devops/*
      - test/*
    paths:
      - .github/**
      - devops/**

jobs:
  devops-tests:
    name: Various tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.ED_25519 }}"
# Add steps to get GHA itself
