---
name: Run PreCommit

on:
  push:
    branches-ignore:
      - master
      - release-*

jobs:
  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Refresh source list
        run: |
          sudo apt update
      - name: Install dependencies
        run: >
          sudo apt install -y
          protobuf-compiler
          pkg-config
          libssl-dev
      - name: Install official Rust
        run: >
          curl
          --proto '=https'
          -y
          --tlsv1.2
          -sSf https://sh.rustup.rs
          | sh
      - name: Install machete
        run: |
          . "$HOME/.cargo/env"
          cargo install cargo-machete
      - name: Install nightly tool chain (for fmt)
        run: |
          rustup toolchain install nightly
      - name: Add nightly fmt
        run: >
          rustup component add
          --toolchain nightly-x86_64-unknown-linux-gnu
          rustfmt
      - name: Install precommit
        run: |
          python -m pip install pre-commit
      - name: Install hooks
        run: |
          pre-commit install --install-hooks
      - name: Run Pre-Commit
        run: >
          pre-commit run
          --all-files
          --show-diff-on-failure
          -v
