---
name: pre-commit

on: [push]

jobs:
  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y rustc cargo protobuf-compiler pkg-config libssl-dev
      - run: rustup toolchain install nightly
      - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
      - run: python -m pip install pre-commit
      - run: pre-commit install --install-hooks
      - run: pre-commit run --show-diff-on-failure --color=never -a
