---
name: Release

on:
  push:
    tags:
      - "client-*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and push binaries to github release page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages for Rust&Cargo
        run: >
          sudo apt install -y
          rustc
          cargo
          protobuf-compiler
          pkg-config
          libssl-dev
      - name: Run tests
        run: |
          cd client
          cargo test
      - name: Build binaries
        run: |
          cd backend
          cargo build --release
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/ivynet
          make_latest: true

build-image:
    name: Build image with packer
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages for TOML (cargo package)
        run: >
          sudo apt install -y
          cargo
      - name: Install toml (package)
        run: |
          cargo install toml-cli
      - name: Create a file with the vault password
        run: echo "$ANSIBLE_VAULT" > ~/.vault.txt
        env:
          ANSIBLE_VAULT: ${{ secrets.ANSIBLE_VAULT }}
      - name: Run Packer
        run: |
          cd devops/packer
          ./cloudstation.sh
