---
name: Release Backend

on:
  push:
    tags:
      - "backend-*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and push binaries to github release page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages for Rust&Cargo
        run: >
          sudo apt install -y
          rustc
          cargo
          protobuf-compiler
          pkg-config
          libssl-dev
      - name: Run tests
        run: |
          cargo test
      - name: Build binaries
        run: |
          cargo build --release
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/ivynet-backend
          make_latest: false
